@startsalt
{^"Dados Gerais"
    n               | " 150"
    max_wth         | "  20"
    max_btw         | "  10"
    mte             | " 500"
    k               | "   5"
    teta            | "0.01"
    nbRep           | "   5"
                    |
                    | [ OK ]
}
@endsalt
